#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash or
#       ksh, you may want to run it with that shell.
#
#   (2) The IFS environment variable causes word splitting when set to a
#       non-default value. This is fixed below.
#
#   (3) Put the Gradle home directory in front of the PATH so that this script
#       finds the right gradle to start.
#
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS
# to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS*|MINGW* )    msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" ; then
    case $( ulimit -S -n ) in       #(
      'unlimited'|2[0-9][0-9][0-9][0-9][0-9][0-9]) ;; #(
      *)                            # Here assume we're running on Linux (not Cygwin or msys)
                                     ulimit -S -n 262144 ;;
    esac
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=$( save "$@" )

# Collect all arguments for the java command, stacking in reverse order:
#   * DEFAULT_JVM_OPTS
#   * JAVA_OPTS
#   * GRADLE_OPTS
#   * Parameters passed to gradlew

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} ; t=/${t%%/*}            # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        # Roll the args list around so we can call save, which will
        # output list of values.
        set -- "$@" "$arg"
    done
    # to separate file names and file arguments from options. This makes proper
    # quoting of arguments have the most effect.
    for arg do
        case $arg in                                #(
          -*)   setIt=no ;;
          *)    setIt=yes ;;
        esac
        case $setIt in                              #(
          yes)  set -- "$@" "$arg"  ;;              #(
          *)    set -- "$@" -J"$arg" ;;             #(
        esac
    done
fi

# Loads a configuration file, optional.
# $1 = config file
# $2 = property name prefix
_load_config() {
    if [ -f "$1" ] ; then
        . "$1"
    fi
}

if _load_config "$APP_HOME/gradle.properties"; then
    :
fi

# For Cygwin or MSYS, use the full path and backslash
if "$cygwin" || "$msys" ; then
    eval "GRADLE_HOME=$( cygpath --path --mixed "$GRADLE_HOME" )"
fi

export GRADLE_HOME

# Invoke the actual gradle script with the passed args.
# shellcheck disable=SC2086
exec "$JAVACMD" "$@" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
